spring:
  application.name: zuul-router
  jackson.serialization.write_dates_as_timestamps: false

zuul:
  routes:
    milkshake-service:
      path: /milkshakes/**
      stripPrefix: false
    banana-service:
      path: /bananas/**
      stripPrefix: false
---
spring:
  profiles: mu

milkshake-service:
  ribbon:
    listOfServers: milkshake-service.${_SERVICE_DISCOVERY_NAME}

banana-service:
  ribbon:
    listOfServers: banana-service.${_SERVICE_DISCOVERY_NAME}
